name: pkb_screen_guard
description: A Flutter plugin that protects screen security (screenshot, recording, mirroring, root/jailbreak detection).
version: 0.0.4
homepage: https://github.com/pirapong/pkb_screen_guard
repository: https://github.com/pirapong/pkb_screen_guard

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pkbstudio.pkbscreenguard
        pluginClass: PkbScreenGuardPlugin
      ios:
        pluginClass: PkbScreenGuardPlugin
